import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import 'rsuite/dist/rsuite-no-reset.min.css';
import "react-international-phone/style.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import "../app/css/globals.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Troovex",
  description: "Generated by Troovex project",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
